/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./components/ArticleItem.vue')['default']
    BoostButton: typeof import('./components/BoostButton.vue')['default']
    Error: typeof import('./components/Error.vue')['default']
    FeedSearch: typeof import('./components/FeedSearch.vue')['default']
    FeedSearch2: typeof import('./components/FeedSearch2.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    SortableList: typeof import('./components/SortableList.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
